### ISSUE TITLE
Error unfortunately, fb has stopped

### ISSUE THREAD

**Issue by crazyshock** [ccsoft/cordova-facebook#70]
When i press the button ~login~ appears this message:

unfortunately, fb has stopped

what's wrong?

**Comment by koraybalci** [comment]
and your platform (android/ios) and facebook sdk version is?

**Comment by over12** [comment]
Fb: 3.18
Api Android: 19

used the same as the plugin.

**Comment by over12** [comment]
My files of my aplicattion
For test my folder with my aplication:
https://www.dropbox.com/sh/qkd4v4c9rqh33u7/AADGdWwNv7AYbO4jJ-O8qMc3a?dl=0

**Comment by koraybalci** [comment]
You can try the sample app linked in readme. It must be working fine, you can use it s a guide.

**Comment by over12** [comment]
Yes ocurred that error:


Error: ENOENT, no such file or directory '/Users/roni/Documents/Downloads/cordova-sample-facebook/libs/android/facebook-android-sdk-3.23.0/facebook/build.xml'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at writeBuildXml (/Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/lib/build.js:96:24)
    at /Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/lib/build.js:104:21
    at _fulfilled (/Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/node_modules/q/q.js:760:13)
    at /Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/node_modules/q/q.js:574:44
    at flush (/Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)
ERROR building one of the platforms: Error: /Users/roni/Documents/Downloads/cordova-sample-facebook/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project

**Comment by over12** [comment]
I compile but gave the same error.

Unfortunately, CordovaSample has stopped.

**Comment by koraybalci** [comment]
I am sorry but, since the sample is working for almost everyone (including me), the problem is on  your end probably. You can try googling the error and repeating the installation step, especially FB SDK related stuff (referencing it, etc.)
